# Generated by Django 5.0.3 on 2024-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motus", "0003_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="life_point",
            field=models.IntegerField(default=6),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_game_per_user"
            ),
        ),
    ]
